### ISSUE TITLE
'fdroid import' as part of this plugin

### ISSUE THREAD

**Issue by eighthave** [openintents/gradle-fdroid-plugin#1]
I'm really happy to see this plugin, thanks for putting it together! One thing I'd like to see is having this plugin automatically generate the fdroid metadata needed to run builds with fdroid.  I see you are following my [git-local fdroid metadata format](https://gitlab.com/fdroid/fdroidserver/merge_requests/62), would `gradle fdroidImport` make sense? Or maybe your gradle plugin would generate the .fdroid.yml every time?  Things like the app description, homepage, main git URL, etc. do not seem to be a standard part of gradle configs, so perhaps this gradle plugin would generate the initial .fdroid.yml, then parse it when it is present.

**Comment by friedger** [comment]
Yes `fdroidImport` can be done. However, I can thing of something more advanced, as it is part of the project already.
Maybe something like `gradle fdroidCreateMeta`? This gradle task could try to gather data 
- from the git repo the project is based on
- from the data of triple-t publisher plugin
- etc

Maybe one can even think something clever when the meta data needs to be recreated.

**Comment by friedger** [comment]
fdroidImport has been added in
https://github.com/openintents/gradle-fdroid-plugin/commit/fe4979886116e51c93b02b478d003e3ecdf3e1cc
